### ISSUE TITLE
issue selecting a table from the current map

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter-scripts#33]
Using either the Moderate or the Email tools:
When I select a table layer as the input layer (eg the comments layer from a Reporter config), I'm having a hard time getting the URL to that layer. The object that is returned is a geoprocessing value object that has no .describe, .properties, or .connectionProperties. 

I can get to the URL if the map containing that layer is active by navigating through the current project and active map properties (thanks @cosbyr !). If the user navigates away from that map after selecting the table, I lose the URL. I also can't get the URL in the first place if that map isn't active, even though the table will show in the drop down.

suggestions?
@chris-fox @cosbyr @ChrisBuscaglia

**Comment by chris-fox** [comment]
I am able to get the url from a table in the map passed to the solution deployment tool 'Modify Domains' tool. Below is a link to the function I wrote to handle this. This has been working in 1.4, 2.0 and 2.1 (Important because what is returned by Pro has changed over those versions). 

https://github.com/ArcGIS/solution-deployment/blob/master/tools/DeploySolutions.pyt#L488

Essentially I am doing this:

desc = arcpy.Describe(parameters[0].value)
url = desc.path

**Comment by allisonmuise** [comment]
This still fails if the map containing the layer goes from being the visible element in the project to hidden before the tool is run. Just changing the tabs, for example from the map to the Catalog, causes error messages to appear in the tool UI.

**Comment by chris-fox** [comment]
Not sure what is different in your scenario but in the SDT using the Update Domain tool I can select a Table from from a Map behind the Catalog view and the validation and execute logic all works to get the url from the table.

![image](https://user-images.githubusercontent.com/6796763/36274900-3a4b9ea6-1257-11e8-8615-e147af379f28.png)

**Comment by allisonmuise** [comment]
it fails on the other logic and validation that goes on when setting the subsequent parameters. Ryan found the same issue with his tool. We are going to try to trap the message and tell users to not change the map view while configuring the tool. There isn't a good reason for them to be changing the view between parameters, anyway, and I think it would be pretty rare for a user to come across this

**Comment by allisonmuise** [comment]
@cosbyr has confirmed that there isn't a good way past this. Internal validation is firing off the errors before we can trap them. There isn't a good way that either of us can find past it. Core tools have the same behavior, so we are both going to let this be as-is in our tools.

**Comment by chris-fox** [comment]
@cosbyr, @allisonmuise, I may still be missing the specific scenario but I made some changes to the Email update params, update messages, and execute in the attached toolbox and it is working for me. I can switch between Map and Catalog, switch the layer/table selections in the first param and no errors.

Without my changes I am finding it is writing the name of the table to the config rather than the url which will cause the script to fail when run outside of Pro. 

I am also running 2.1 if that makes a difference.

[ServiceSupport.zip](https://github.com/Esri/crowdsource-reporter-scripts/files/1729431/ServiceSupport.zip)

**Comment by cosbyr** [comment]
I believe this one happened when you switch from one map to another map, not necessarily between map and catalog. When one map has a layer that the tool references and you switch to another map that doesn't have that layer... it gives an error.

**Comment by chris-fox** [comment]
@cosbyr, @allisonmuise mentioned you saw the error with core gp tools as well, Could you send me the repro case. I would like to report it to the GP team to fix so we don't have to workaround this using the arcpy.mp package to iterate the active map's tables.

**Comment by cosbyr** [comment]
@chris-fox I'm struggling to come up with a repro case right now. If i can remember what core GP tool I was testing it on I will let you know. Sorry.
